### ISSUE TITLE
Positioning issues with core_load_step_with_colors.py

### ISSUE THREAD

**Issue by Rayfoundry** [tpaviot/pythonocc-demos#5]
Using the core_load_step_with_colors.py example displays parts in incorrect positions. 

However loading the SEP file with STEPControl_Reader as a single shape, positions the elements correctly. Please see screenshots attached. 

File can be downloaded [here](https://drive.google.com/open?id=1JwqhohSFPgFCQP06sLJ4LfYFyInvrwtZ)

![screenshot from 2018-06-16 19-17-51](https://user-images.githubusercontent.com/20320596/41500964-c013fc24-719b-11e8-95c8-57a3dda15d00.png)
![screenshot from 2018-06-16 19-19-07](https://user-images.githubusercontent.com/20320596/41500965-c02d2c4e-719b-11e8-9645-e58d16a1100f.png)

**Comment by tpaviot** [comment]
Fixed in current master with latest pythonocc-core
![pyocc_scr](https://user-images.githubusercontent.com/660130/49699552-d597cf00-fbd2-11e8-8224-af436522c652.png)
