### ISSUE TITLE
Possible to export STEP file with colors to X3D?

### ISSUE THREAD

**Issue by wzbernstein** [tpaviot/pythonocc-demos#7]
I am trying to merge the two examples, core_load_step_with_colors and x3d_export, but am running into problems in defining the complete shape so that I can export to x3d and still have persistent coloring.  Any ideas?  According to a PPT online, it is not possible to export x3d with color using pythonocc (see: http://www.web3d.org/sites/default/files/presentations/STEP%20to%20X3D%20Conversion%20Routes/STEP_TO_X3D.pdf)

**Comment by tpaviot** [comment]
Fixed by both commits https://github.com/tpaviot/pythonocc-core/commit/a0a6b6f1d20ecadac4bdc4912b7d4e3b8bfe17b5 and https://github.com/tpaviot/pythonocc-demos/commit/ff7e3747c6182c0bc99b697086bf0924bc1e44be

Result can be viewed online at https://tpaviot.github.io/webgl/STEP_to_X3D_cax_if/
