### ISSUE TITLE
Example for automatically sizing the Display3d widget?

### ISSUE THREAD

**Issue by nsmela** [tpaviot/pythonocc-demos#72]
Hi there,

I'm having a hard time getting the display in PyQt5 to fully fit into a window. If I resize the window, it then works great.

I've tried:

- self.display.ResetView()
- self.display.View.MustBeResized()
- self.layout().addWidget(self.canvas, stretch=1)

Any other suggestions?

**Comment by tpaviot** [comment]
The resize event has to be raised from PyQtitself. See for instance https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/SimpleGui.py#L213 where I have to set the window size twice to get sure the occ widget fit the parent window.

**Comment by tpaviot** [comment]
So far, I did not find any better solution

**Comment by nsmela** [comment]
Given the example there, I created a function for my window:

```   def showProperly(self):
        size = [self.size().width(), self.size().height()]
        self.resize(size[0]-1, size[1]-1)
        self.show()
        self.resize(size[0], size[1])```

I couldn't call the window.show() function the same way since I'm using a splash screen, so I use this function instead of calling window.show() in the main file.
